source 'https://rubygems.org'
gem 'rack'
gem 'json'
gem 'activerecord', '~>3.2.14'
gem 'grape'
gem 'rack-cors'
gem 'grape-entity'
gem 'rack-test'
gem 'mongo_mapper'
gem 'geocoder'
gem 'rspec'
gem 'airborne'
gem 'gcm'
gem 'geokit'
gem 'dotenv'